@startuml
state NewHeight : enterNewRound
NewHeight --> Propose : Enter (CreateEmptyBlocks):\n from enterNewRound(height,round)
NewHeight --> Propose : Enter (CreateEmptyBlocks, \n CreateEmptyBlocksInterval > 0 ) \n after enterNewRound(height,round),\n after timeout of CreateEmptyBlocksInterval
NewHeight --> Propose : Enter (!CreateEmptyBlocks) : \nafter enterNewRound(height,round),\n once txs are in the mempool
state Propose {
state enterPropose: consensus.scheduleTimeout(RoundStepPropose)\nisProposer:defaultDecideProposal
}
@enduml